#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    #colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    windows_leader = "s"
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false
    spacevim_wrap_line = true
    # windows_smartclose = ''
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    snippet_engine = "ultisnips"
    project_rooter_patterns = ['.git/']
    project_rooter_outermost = false
    autocomplete_method = "deoplete"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
auto_completion_enable_snippets_in_popup = true

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 40

[[layers]]
name = 'edit'
autosave_events = ['InsertLeave', 'TextChanged']
autosave_all_buffers = true

[[layers]]
name = "lang#python"
python_interpreter = "/usr/bin/python"
format_on_save = true
enabled_linters = ['python', 'pylint']

[[layers]]
name = "lang#c"
# enable_clang_syntax_highlight = true

[[layers]]
name = 'lang#cmake'

[[layers]]
name = 'lang#latex'

[[layers]]
name = "lsp"
enabled_clients = ['vimls','pyright','clangd','bash-language-server']
  filetypes = [
    "python",
    "cpp"
  ]

[[custom_plugins]]
repo = "folke/tokyonight.nvim"
merged = false

[[custom_plugins]]
repo = "numirias/semshi"
merged = false

[[custom_plugins]]
repo = "jackguo380/vim-lsp-cxx-highlight"
merged = false

# to generate the docstring
[[custom_plugins]]
repo = "kkoomen/vim-doge"
merged = false

[[layers]]
name = "chinese"

[[layers]]
name = "checker"
lint_engine = "ale"

[[layers]]
name = "sudo"

[[layers]]
name = 'git'
git_plugin = 'git'
git_diff_position = 'vsplit'
  
# [[layers]]
# name = "treesitter"

[[layers]]
name = "ctrlspace"
autoload-workspaces = true
autosave-workspaces = true

[[layers]]
name = 'ui'
enable_sidebar = true
enable_scrollbar = true
# enable_indentline = true
# enable_cursorword = false
# indentline_char = '|'
# conceallevel = 0
# concealcursor = ''
# cursorword_delay = 50
# cursorword_exclude_filetype = []
# indentline_exclude_filetype = []

[[layers]]
name = "github"

[[layers]]
name = "leaderf"

