function filebrowser-here --description 'Serve a directory with an ephemeral File Browser instance'
    argparse h/help 'p/port=' no-auth open -- $argv
    or return 2

    if set -q _flag_help
        echo "Usage: filebrowser-here [--port PORT] [--no-auth] [--open] [DIRECTORY]"
        echo
        echo "Options:"
        echo "  -h, --help       Show this help."
        echo "  -p, --port PORT  Listen on PORT instead of choosing an available port."
        echo "      --no-auth    Disable authentication for this instance."
        echo "      --open       Open the URL in the system browser after starting."
        echo
        echo "Serves DIRECTORY (the current directory by default) using a temporary"
        echo "File Browser database that is removed when the server exits. Without"
        echo "--no-auth, File Browser prints a generated password for the admin user."
        echo
        echo "The server binds to 127.0.0.1 by default. If IP_PREFIX is set, the first"
        echo "matching global IPv4 address is selected, bound, and advertised instead."
        echo
        echo "Examples:"
        echo "  filebrowser-here"
        echo "  filebrowser-here ~/Downloads"
        echo "  filebrowser-here --port 8090 ~/Downloads"
        echo "  filebrowser-here --no-auth ~/Downloads"
        echo "  set -gx IP_PREFIX 10.32.; filebrowser-here ~/Downloads"
        return 0
    end

    if test (count $argv) -gt 1
        echo "Expected at most one DIRECTORY argument." >&2
        return 2
    end

    if not command -q filebrowser
        echo "filebrowser not found on PATH; run 'mise install' first" >&2
        return 127
    end

    set -l directory .
    if test (count $argv) -eq 1
        set directory $argv[1]
    end
    if not test -d "$directory"
        echo "Directory not found: $directory" >&2
        return 1
    end

    set -l root (path resolve -- "$directory")
    or begin
        echo "Unable to resolve directory: $directory" >&2
        return 1
    end

    set -l host 127.0.0.1
    if set -q IP_PREFIX; and test -n "$IP_PREFIX"
        if not command -q ip
            echo "IP_PREFIX is set, but ip(8) was not found on PATH" >&2
            return 127
        end

        set -l matched_ips
        for ip_addr in (ip -o -4 addr show scope global | awk '{split($4, a, "/"); print a[1]}')
            if string match -q "$IP_PREFIX*" -- "$ip_addr"
                set -a matched_ips "$ip_addr"
            end
        end

        if test (count $matched_ips) -eq 0
            echo "No IPv4 address matched IP_PREFIX=$IP_PREFIX" >&2
            return 1
        end

        set host $matched_ips[1]
        if test (count $matched_ips) -gt 1
            echo "Multiple IPv4 addresses matched IP_PREFIX=$IP_PREFIX; using $host" >&2
        end
    end

    set -l port
    if set -q _flag_port
        set port $_flag_port
        if not string match -qr '^[0-9]+$' -- "$port"; or test "$port" -lt 1; or test "$port" -gt 65535
            echo "Invalid port: $port" >&2
            return 2
        end
    else
        set -l python_bin
        if command -q python
            set python_bin (command -s python)
        else if command -q python3
            set python_bin (command -s python3)
        else
            echo "python or python3 is required to choose an available port; pass --port PORT instead" >&2
            return 127
        end

        set port ($python_bin -c 'import socket, sys; host = sys.argv[1]; s = socket.socket(); s.bind((host, 0)); print(s.getsockname()[1]); s.close()' "$host")
        or return $status
    end

    set -l opener
    if set -q _flag_open
        if command -q xdg-open
            set opener (command -s xdg-open)
        else if command -q open
            set opener (command -s open)
        else
            echo "--open was requested, but neither xdg-open nor open was found" >&2
            return 127
        end
    end

    set -l temp_dir (mktemp -d -t filebrowser.XXXXXX)
    or begin
        echo "Unable to create a temporary File Browser directory" >&2
        return 1
    end

    set -l database "$temp_dir/filebrowser.db"
    set -l url "http://$host:$port"
    set -l filebrowser_args \
        --database "$database" \
        --root "$root" \
        --address "$host" \
        --port "$port"

    if set -q _flag_no_auth
        set -a filebrowser_args --noauth
    end

    echo "File Browser root: $root"
    echo "File Browser URL:  $url"
    echo "Database:          temporary; removed when the server exits"
    if set -q _flag_no_auth
        echo "Authentication:    disabled; anyone with access to the URL can modify files"
    else
        echo "Username:          admin"
        echo "Password:          generated by File Browser and printed below"
    end
    echo "Press Ctrl-C to stop."

    if test -n "$opener"
        begin
            sleep 1
            "$opener" "$url" >/dev/null 2>&1
        end &
    end

    filebrowser $filebrowser_args
    set -l filebrowser_status $status

    rm -rf -- "$temp_dir"
    return $filebrowser_status
end
